allow workflow dispatch (#545)

diff --git a/.github/actions/docker-image-version/action.yaml b/.github/actions/docker-image-version/action.yaml
--- a/.github/actions/docker-image-version/action.yaml
+++ b/.github/actions/docker-image-version/action.yaml
@@ -2,6 +2,12 @@ name: Docker - Generate image version
 description: |
   Release versions use short hashes. All other versions are generated using long hashes and have a pr number appended.
 
+inputs:
+  allow-dispatch:
+    description: Is workflow dispatch allowed to generate a docker image version
+    required: true
+    default: false
+
 outputs:
   version:
     description: The resulting version
@@ -10,24 +16,25 @@ outputs:
 runs:
   using: composite
   steps:
-    - name: Guard against non-supported events
-      if: ${{ github.event_name != 'push' && github.event_name != 'pull_request' }}
-      shell: bash
-      run: |
-        echo "::error:: Only "push" and "pull_request" events are supported by this action."
-        exit 1
-
     - name: Generate version
       id: output
       shell: bash
       run: |
-        if [ "$GITHUB_EVENT_NAME" = 'push' ] && [ "$GITHUB_REF_NAME" = 'main' ]; then
-          version="$(git rev-parse --short $GITHUB_SHA)"
-        elif [ "$GITHUB_EVENT_NAME" = 'pull_request' ]; then
-          version="${GITHUB_SHA}-pr.${{ github.event.pull_request.number }}"
+        if [ "${{ github.event_name }}" = 'push' ] && [ "${{ github.ref_name }}" = 'main' ]; then
+          version="$(git rev-parse --short ${{ github.sha }})"
+        elif [ "${{ github.event_name }}" = 'pull_request' ]; then
+          version="${{ github.sha }}-pr.${{ github.event.pull_request.number }}"
+        elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ ${{ inputs.allow-dispatch }} ]; then
+          if [ "${{ github.ref_name }}" = 'main' ]; then
+            version="$(git rev-parse --short ${{ github.sha }})"
+          else
+            sanitized_branch=$(printf '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9]//g') 
+            version="${{ github.sha }}.${sanitized_branch}"
+          fi
         else
-          >&2 echo "::error:: Not supported on push to branches other than main"
+          >&2 echo "::error:: Unsupported invocation: ${{ github.event_name }}"
           exit 1
         fi
         echo "version=${version}" >> $GITHUB_OUTPUT
         echo "version=${version}" >> $GITHUB_ENV
+        echo "version: $version"
