1745 eliminate charts (#402)

diff --git a/.github/workflows/build-domain.yaml b/.github/workflows/build-domain.yaml
--- a/.github/workflows/build-domain.yaml
+++ b/.github/workflows/build-domain.yaml
@@ -8,8 +8,7 @@ jobs:
     name: Setup
     runs-on: ubuntu-latest
     outputs:
-      domains: ${{ env.domains }}
-      projects: ${{ env.projects }}
+      matrix: ${{ env.matrix }}
 
     steps:
       - uses: actions/checkout@v3
@@ -29,18 +28,10 @@ jobs:
             required_folder "$domain/.devcontainer"
             required_file "$domain/.devcontainer/Dockerfile"
             required_file "$domain/.devcontainer/devcontainer.json"
-
             required_file "$domain"/*.sln
-
-            required_folder "$domain/chart"
-            required_file "$domain/chart/Chart.yaml"
-            required_file "$domain/chart/values.yaml"
-
-            find "$domain" -mindepth 3 -maxdepth 3 -name "*.csproj" -exec dirname {} \; | egrep -v '[^\/]*/[^\/]*/Shared/[^\/]*' | egrep -v 'Tests$' | while read project; do
-              location=$(dirname "$project")
-              required_file "$location/chart-overrides.yaml"
-            done
-
+            if [ ! -f "$domain/configuration.yaml" ]; then
+              find "$domain" -name configuration.yaml -mindepth 2 -maxdepth 2 -type f | read || { printf '::error title=Missing file::%s/configuration.yaml\n' "$domain"; exit 1; }
+            fi
           done
 
       - uses: CodeReaper/find-diff-action@v3
@@ -48,65 +39,50 @@ jobs:
         with:
           paths: domains/*/
 
-      - name: Set default matrices
+      - name: Set default matrix
         shell: bash
         run: |
-          echo "domains=[]" >> "$GITHUB_ENV"
-          echo "projects=[]" >> "$GITHUB_ENV"
+          echo "matrix=[]" >> "$GITHUB_ENV"
 
-      - name: Build relevant domain/project matrices
+      - name: Build relevant matrix
         if: ${{ steps.diff.outputs.list != '' }}
         shell: bash
         env:
           LIST: ${{ steps.diff.outputs.list }}
         run: |
           matrix=$(while read domain; do
-            [ -f "$domain/domain.json" ] || echo "{}" > "$domain/domain.json"
-            echo '{"draft": false}' > "$domain/default.domain.json"
             [ -f "$domain/global.json" ] || cp "$domain/../../global.json" "$domain/global.json"
-            settings=$(jq -srec '.[0] * .[1] * .[2] | .path=$path' --arg path "$domain" "$domain/default.domain.json" "$domain/domain.json" "$domain/global.json")
+            settings=$(jq -srec '.[0] | .path=$path' --arg path "$domain" "$domain/global.json")
 
-            draft=$(printf '%s' "$settings" | jq -rce '.draft')
             sdk=$(printf '%s' "$settings" | jq -rce '.sdk.version')
-            projects=$(find "$domain" -mindepth 3 -maxdepth 3 -name "*.csproj" -exec dirname {} \; | egrep -v '[^\/]*/[^\/]*/Shared/[^\/]*' | egrep -v 'Tests$' | while read directory; do printf '{"path":"%s","draft":"%s","dotnetVersion":"%s"}' "$directory" "$draft" "$sdk"; done | jq -sc '.')
+            projects=$(find "$domain" -mindepth 3 -maxdepth 3 -name "*.csproj" -exec dirname {} \; | egrep -v '[^\/]*/[^\/]*/Shared/[^\/]*' | egrep -v 'Tests$' | while read directory; do printf '{"path":"%s","dotnetVersion":"%s"}' "$directory" "$sdk"; done | jq -sc '.')
 
-            printf '{"domain":%s,"projects":%s}' "$settings" "$projects"
+            printf '{"projects":%s}' "$projects"
           done <<< $LIST | jq -sc '.')
 
           echo '::group::Matrix'
           echo "$matrix" | jq -r '.'
           echo '::endgroup::'
 
-          domains=$(printf "$matrix" | jq -cr '[.[].domain] | unique')
-          echo "domains=$domains" >> "$GITHUB_ENV"
-
           projects=$(printf "$matrix" | jq '.[].projects[]' | jq -scr '. | unique')
-          echo "projects=$projects" >> "$GITHUB_ENV"
+          echo "matrix=$projects" >> "$GITHUB_ENV"
 
-      - name: Relevant domains
+      - name: Matrix
         shell: bash
         run: |
           echo '::group::Raw'
-          printf '${{ env.domains }}\n'
+          printf '${{ env.matrix }}\n'
           echo '::endgroup::'
-          printf '${{ env.domains }}' | jq -r '.'
-
-      - name: Relevant projects
-        shell: bash
-        run: |
-          echo '::group::Raw'
-          printf '${{ env.projects }}\n'
-          echo '::endgroup::'
-          printf '${{ env.projects }}' | jq -r '.'
+          printf '${{ env.matrix }}' | jq -r '.'
 
   build-projects:
     name: Build projects
     runs-on: ubuntu-latest
     needs: setup
-    if: ${{ needs.setup.outputs.projects != '[]' }}
+    if: ${{ needs.setup.outputs.matrix != '[]' }}
     strategy:
       matrix:
-        build: ${{ fromJson(needs.setup.outputs.projects) }}
+        build: ${{ fromJson(needs.setup.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v3
 
@@ -120,12 +96,13 @@ jobs:
           docker="$PROJECT/Dockerfile"
           service=$(dirname "$PROJECT")
           domain=$(dirname "$service")
-          overrides="${service}/chart-overrides.yaml"
-          name=$(basename $(yq '.name' "$overrides"))
-
-          tag=$(yq '.version' "$overrides")
+          configuration="${domain}/configuration.yaml"
+          if [ ! -f "$configuration" ]; then
+            configuration="${service}/configuration.yaml"
+          fi
+          name=$(yq '.name' "$configuration")
+          tag=$(yq '.version' "$configuration")
           tag=$(sh ./.github/tooling/semver.sh "$tag" "$PR")
-
           dotnet=${{ matrix.build.dotnetVersion }}
 
           {
@@ -155,118 +132,41 @@ jobs:
           image-name: ${{ steps.resolver.outputs.name }}
           image-tag: ${{ steps.resolver.outputs.tag }}
           docker-context: ${{ steps.resolver.outputs.domain }}
-          dry-run: ${{ matrix.build.draft }}
+          dry-run: ${{ !(github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'preview/')) }}
           build-args: |
             SDK_VERSION=${{ matrix.build.dotnetVersion }}
             RUNTIME_VERSION=${{ steps.resolver.outputs.dotnet }}
-
-  build-chart:
-    name: Build chart
-    runs-on: ubuntu-latest
-    needs:
-      - setup
-      - build-projects
-    if: ${{ needs.setup.outputs.domains != '[]' }}
-    concurrency: commits-charts
-    strategy:
-      max-parallel: 1
-      matrix:
-        build: ${{ fromJson(needs.setup.outputs.domains) }}
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Resolve paths
-        shell: bash
-        id: resolve-paths
-        env:
-          DOMAIN: ${{ matrix.build.path }}
-        run: |
-          chart="$DOMAIN/chart"
-          echo "domain=${DOMAIN}" >> $GITHUB_OUTPUT
-          echo "chart=${chart}" >> $GITHUB_OUTPUT
-
-      - name: Apply chart overrides
-        shell: bash
-        env:
-          DOMAIN: ${{ steps.resolve-paths.outputs.domain }}
-          PROJECTS: ${{ needs.setup.outputs.projects }}
-          PR: ${{ github.event.pull_request.number }}
-        run: |
-          output="$DOMAIN/chart/values.yaml"
-          printf '%s' "$PROJECTS" | jq -r '.[].path' | grep ^$DOMAIN | while read project; do
-              input="$project/../chart-overrides.yaml"
-              value=$(yq '.version' "$input")
-              value=$(sh ./.github/tooling/semver.sh "$value" "$PR")
-              path=$(yq '.versionPath' "$input")
-              yq -i ".$path = \"$value\"" "$output"
-
-              value=$(yq '.name' "$input")
-              path=$(yq '.namePath' "$input")
-              yq -i ".$path = \"$value\"" "$output"
-          done
-
-      - name: Resolve chart version
-        id: resolve-chart
-        uses: ./.github/actions/yaml-semver
-        with:
-          yaml-file: ${{ steps.resolve-paths.outputs.chart }}/Chart.yaml
-          yaml-path: version
-
-      - name: Release chart
-        id: release-chart
-        uses: ./.github/actions/helm-release-chart
-        with:
-          chart_folder: ${{ steps.resolve-paths.outputs.chart }}
-          chart_version: ${{ steps.resolve-chart.outputs.semver }}
-          include_image_name: true
-          deploy_key: ${{ secrets.DEPLOY_KEY_HELM_CHARTS }}
-          dry_run: ${{ matrix.build.draft }}
 
   update-environment:
     name: Update environment
     runs-on: ubuntu-latest
     needs:
       - setup
-      - build-chart
+      - build-projects
     concurrency: commits-base-environment
     strategy:
       max-parallel: 1
       matrix:
-        build: ${{ fromJson(needs.setup.outputs.domains) }}
+        build: ${{ fromJson(needs.setup.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v3
 
-      - name: Resolve paths
+      - name: Resolve
         shell: bash
-        id: resolve-paths
         env:
-          DOMAIN: ${{ matrix.build.path }}
+          PROJECT: ${{ matrix.build.path }}
         run: |
-          chart="$DOMAIN/chart"
-          echo "chart=${chart}" >> $GITHUB_OUTPUT
-
-      - name: Resolve chart version
-        id: resolve-chart
-        uses: ./.github/actions/yaml-semver
-        with:
-          yaml-file: ${{ steps.resolve-paths.outputs.chart }}/Chart.yaml
-          yaml-path: version
-
-      - name: Get info from Chart.yaml
-        id: chart-info
-        uses: ./.github/actions/chart-info
-        with:
-          chart-folder: ${{ steps.resolve-paths.outputs.chart }}
-          chart-version: ${{ steps.resolve-chart.outputs.semver }}
-          include-image-name: true
+          service=$(dirname "$PROJECT")
+          domain=$(dirname "$service")
+          configuration="${domain}/configuration.yaml"
+          if [ ! -f "$configuration" ]; then
+            configuration="${service}/configuration.yaml"
+          fi
+          echo "configuration=${configuration}" >> $GITHUB_ENV
 
       - name: Update environment
         uses: ./.github/actions/update-base-environment
-        if: github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'preview/')
         with:
-          env_branch: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'main' || github.event.pull_request.head.ref }}
-          app_name: ${{ steps.chart-info.outputs.chart-name }}
-          chart_name: ${{ steps.chart-info.outputs.chart-name }}
-          chart_version: ${{ steps.resolve-chart.outputs.semver }}
+          configuration: ${{ env.configuration }}
           deploy_key: ${{ secrets.DEPLOY_KEY_BASE_ENVIRONMENT }}
-          dry_run: ${{ matrix.build.draft }}
+          dry_run: ${{ !(github.event_name == 'push' && github.ref_name == 'main' || github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'preview/')) }}
