sheesh

diff --git a/.github/workflows/build-subsystems.yaml b/.github/workflows/build-subsystems.yaml
--- a/.github/workflows/build-subsystems.yaml
+++ b/.github/workflows/build-subsystems.yaml
@@ -14,11 +14,31 @@ on:
 
 jobs:
   setup:
+    name: Setup
     runs-on: ubuntu-latest
     outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      matrix: ${{ env.matrix }}
+
     steps:
       - uses: actions/checkout@v4
+
+      - name: Validate required domain structure
+        shell: bash
+        run: |
+          function required_folder {
+            [ -d "$1" ] || { printf '::error title=Missing folder::%s\n' "$1"; exit 1; }
+          }
+
+          function required_file {
+            [ -f "$1" ] || { printf '::error title=Missing file::%s\n' "$1"; exit 1; }
+          }
+
+          find domains -mindepth 1 -maxdepth 1 -type d | while read domain; do
+            required_folder "$domain/.devcontainer"
+            required_file "$domain/.devcontainer/Dockerfile"
+            required_file "$domain/.devcontainer/devcontainer.json"
+            required_file "$domain"/*.sln
+          done
 
       - uses: CodeReaper/find-diff-action@v3
         id: diff
@@ -31,7 +51,7 @@ jobs:
           echo "matrix=[]" >> "$GITHUB_ENV"
 
       - name: Build relevant matrix
-        id: set-matrix
+        if: ${{ steps.diff.outputs.list != '' }}
         shell: bash
         env:
           LIST: ${{ steps.diff.outputs.list }}
@@ -42,21 +62,10 @@ jobs:
             settings=$(jq -srec '.[0] | .path=$path' --arg path "$domain" "$domain/global.json")
             sdk=$(printf '%s' "$settings" | jq -rce '.sdk.version')
             runtime=$(printf '%s' "$settings" | jq -rce '.runtime.version')
-            csprojects=$(find "$domain" -mindepth 3 -maxdepth 3 -name "*.csproj" -exec dirname {} \;)
-
-            projects=$(while read project; do
-              config_file="$(dirname $project)/configuration.yaml"
-              migration_file="$(dirname $project)/migrations/API.sql"
-              has_migration="false"
-              if [ -f "$migration_file" ]; then
-                has_migration="true"
-              fi
-              if [ -f "$config_file" ]; then
-                printf '{"name":"%s","projectPath":"%s","configuration":"%s","sdkVersion":"%s","runtimeVersion":"%s","hasMigration":"%s","migration":"%s"}\n' \
-                "$(basename $domain)" "$project" "$config_file" "$sdk" "$runtime" "$has_migration" "$migration_file"
-              fi
-            done <<< "$csprojects" | jq -sc '.')
-          done <<< "$LIST" > /tmp/json
+            csprojects=$(find "$domain" -mindepth 3 -maxdepth 3 -name "*.csproj" -exec dirname {} \; | egrep -v '[^\/]*/[^\/]*/Shared/[^\/]*' | egrep -v 'Tests$')
+            projects=$(while read project; do printf '{"path":"%s","configuration":"%s","sdkVersion":"%s","runtimeVersion":"%s"}' "$project" "$(dirname $project)/configuration.yaml" "$sdk" "$runtime"; done <<< $csprojects | jq -sc '.')
+            printf '{"projects":%s}\n' "$projects"
+          done <<< $LIST > /tmp/json
 
           if [ ! -s /tmp/json ]; then
             exit 0
@@ -68,7 +77,7 @@ jobs:
           echo '::endgroup::'
 
           projects=$(printf "$matrix" | jq '.[].projects[]' | jq -scr '. | unique')
-          echo "matrix=$matrix" >> "$GITHUB_ENV"
+          echo "matrix=$projects" >> "$GITHUB_ENV"
 
       - name: Matrix
         shell: bash
@@ -78,115 +87,114 @@ jobs:
           echo '::endgroup::'
           printf '${{ env.matrix }}' | jq -r '.'
 
-  test:
-    needs: setup
+  build-projects:
+    name: Build projects
     runs-on: ubuntu-latest
+    needs: setup
+    if: ${{ needs.setup.outputs.matrix != '[]' }}
     strategy:
       matrix:
-        domain: ${{ fromJson(needs.setup.outputs.matrix) }}
-      fail-fast: false
+        build: ${{ fromJson(needs.setup.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
 
-      - name: Setup .NET SDK
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: '8.0.402'
+      - name: Resolve version
+        uses: Energinet-DataHub/acorn-actions/actions/docker-image-version@v1
 
-      - name: Create dynamic solution file for ${{ matrix.domain.name }}
+      - name: Resolve
+        shell: bash
+        env:
+          PROJECT: ${{ matrix.build.path }}
+          CONFIGURATION: ${{ matrix.build.configuration }}
+        run: |
+          projects=$(dirname "$PROJECT")
+          domain=$(dirname "$projects")
+          name=$(yq '.name' "$CONFIGURATION")
+          service=${PROJECT#"$domain"}
+          path=$(find "$PROJECT" -name "*.csproj" | head -n1)
+          paths=$(for item in $(echo "$projects/"* "$projects"/../Shared); do test -d "$item" && find "$item" -name "*.csproj" || true; done)
+          migration="$domain/migrations/$(basename "$PROJECT").sql"
+          if [ ! -f "$migration" ]; then
+            migration=""
+          fi
+
+          EOF=$(head -c 20 /dev/random | md5sum | head -c 32)
+          {
+            printf "paths<<%s\n" "$EOF"
+            printf "%s\n" "$paths"
+            printf "%s\n" "$EOF"
+            echo "migration=${migration}"
+            echo "service=${service}"
+            echo "domain=${domain}"
+            echo "name=${name}"
+            echo "path=${path}"
+          } >> $GITHUB_ENV
+
+      - name: Validate project
+        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') }} == false
+        uses: Energinet-DataHub/acorn-actions/actions/dotnet-validate@v1
+        with:
+          dotnet-version: ${{ matrix.build.sdkVersion }}
+          pin-version: true
+          paths: ${{ env.paths }}
+          sql-file: ${{ env.migration }}
+
+      - name: Ensure files and folders exists
+        shell: bash
+        run: mkdir "${{ env.domain }}/migrations" || true
+
+      - name: Enforce assembly name
         shell: bash
         run: |
-          rm -f EnergyTrackAndTrace.sln
-          dotnet new sln -n ${{ matrix.domain.name }}
-          find domains/${{ matrix.domain.name }} -name '*.csproj' | while read project; do
-            dotnet sln ${{ matrix.domain.name }}.sln add "$project"
-          done
+          set +e
+          grep -q "<AssemblyName>" "${{ env.path }}"
+          if [ $? -eq 0 ]; then
+            sed -i "${{ env.path }}" -e "s|<AssemblyName>.*</AssemblyName>|<AssemblyName>main</AssemblyName>|"
+          else
+            sed -i "${{ env.path }}" -e "s|</PropertyGroup>|<AssemblyName>main</AssemblyName></PropertyGroup>|"
+          fi
 
-      - name: Run tests for ${{ matrix.domain.name }}
-        uses: ./.github/actions/dotnet-test
-        with:
-          solution: ${{ matrix.domain.name }}.sln
-
-  build:
-    needs: setup
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        project: ${{ fromJson(needs.setup.outputs.matrix) }}
-      fail-fast: false
-    steps:
       - uses: actions/checkout@v4
-
-      - name: Build ${{ matrix.project.name }}
-        uses: ./.github/actions/dotnet-build
         with:
-          solution: ${{ matrix.domain.name }}.sln
-          project: ${{ matrix.project.projectPath }}
-          configuration: ${{ matrix.project.configuration }}
-          migrations: ${{ matrix.project.migration }}
+          repository: "Energinet-DataHub/acorn-actions"
+          sparse-checkout: Dockerfile
+          path: acorn-actions
+
+      - name: Copy dockerfile to root path
+        run: cp acorn-actions/Dockerfile .
+
+      - name: Build image
+        uses: Energinet-DataHub/acorn-actions/actions/docker-build-and-push@v1
+        with:
+          dockerfile: Dockerfile
+          image-name: ${{ env.name }}
+          image-tag: ${{ env.version }}
+          docker-context: .
           dry-run: ${{ inputs.dry-run }}
+          build-args: |
+            SUBSYSTEM=${{ env.domain }}
+            PROJECT=${{ env.service }}
+            SDK_VERSION=${{ matrix.build.sdkVersion }}
+            RUNTIME_VERSION=${{ matrix.build.runtimeVersion }}
 
-#  build-authorization:
-#    needs: setup
-#    if: needs.setup.outputs.authorization == 'true'
-#    uses: ./.github/workflows/build-authorization.yaml
-#    secrets: inherit
-#    with:
-#      dry-run: ${{ inputs.dry-run }}
-#      is-dependabot: ${{ inputs.is-dependabot }}
-#
-#  build-certificates:
-#    needs: setup
-#    if: needs.setup.outputs.certificates == 'true'
-#    uses: ./.github/workflows/build-certificates.yaml
-#    secrets: inherit
-#    with:
-#      dry-run: ${{ inputs.dry-run }}
-#      is-dependabot: ${{ inputs.is-dependabot }}
-#
-#  build-measurements:
-#    needs: setup
-#    if: needs.setup.outputs.measurements == 'true'
-#    uses: ./.github/workflows/build-measurements.yaml
-#    secrets: inherit
-#    with:
-#      dry-run: ${{ inputs.dry-run }}
-#      is-dependabot: ${{ inputs.is-dependabot }}
-#
-#  build-oidc-mock:
-#    needs: setup
-#    if: needs.setup.outputs.oidc-mock == 'true'
-#    uses: ./.github/workflows/build-oidc-mock.yaml
-#    secrets: inherit
-#    with:
-#      dry-run: ${{ inputs.dry-run }}
-#      is-dependabot: ${{ inputs.is-dependabot }}
-#
-##  build-open-api:
-##    needs: setup
-##    if: needs.setup.outputs.open-api == 'true'
-##    uses: ./.github/workflows/build-open-api.yaml
-##    secrets: inherit
-##    with:
-##      dry-run: ${{ inputs.dry-run }}
-##      is-dependabot: ${{ inputs.is-dependabot }}
-#
-#  build-transfer:
-#    needs: setup
-#    if: needs.setup.outputs.transfer == 'true'
-#    uses: ./.github/workflows/build-transfer.yaml
-#    secrets: inherit
-#    with:
-#      dry-run: ${{ inputs.dry-run }}
-#      is-dependabot: ${{ inputs.is-dependabot }}
+      - name: Scan image
+        uses: Energinet-DataHub/acorn-actions/actions/docker-scan@v1
+        with:
+          image-name: ${{ env.name }}
+          image-tag: ${{ env.version }}
+          upload-sarif: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
 
-  update:
-    runs-on: ubuntu-latest
+  update-environment:
     name: Update environment
+    runs-on: ubuntu-latest
     needs:
-      - test
-      - build
+      - setup
+      - build-projects
     concurrency: commits-base-environment
+    strategy:
+      max-parallel: 1
+      matrix:
+        build: ${{ fromJson(needs.setup.outputs.matrix) }}
     if: ${{ inputs.is-dependabot == 'false' }}
     steps:
       - uses: actions/checkout@v4
@@ -194,14 +202,6 @@ jobs:
       - name: Update environment
         uses: Energinet-DataHub/acorn-actions/actions/update-base-environment@v1
         with:
-          configurations: |
-            domains/authorization/Authorization.API/configuration.yaml
-            domains/authorization/Proxy/configuration.yaml
-            domains/certificates/Query.API/configuration.yaml
-            domains/measurements/Measurements.API/configuration.yaml
-            domains/oidc-mock/API/configuration.yaml
-            domains/transfer/Transfer.API/configuration.yaml
-            domains/transfer/ClaimAutomation/configuration.yaml
-            domains/transfer/TransferAgreementAutomation/configuration.yaml
+          configuration: ${{ matrix.build.configuration }}
           deploy_key: ${{ secrets.DEPLOY_KEY_BASE_ENVIRONMENT }}
           dry_run: ${{ inputs.dry-run }}
