plz work

diff --git a/.github/workflows/cron-healthcheck.yaml b/.github/workflows/cron-healthcheck.yaml
--- a/.github/workflows/cron-healthcheck.yaml
+++ b/.github/workflows/cron-healthcheck.yaml
@@ -41,55 +41,55 @@ jobs:
         shell: bash
         run: echo "dockers=$(find libraries/docker/ -mindepth 1 -maxdepth 1 -type d | jq -nRc '[inputs]')" >> "$GITHUB_ENV"
 
-  test-subsystems:
-    name: Test subsystems
-    runs-on: ubuntu-latest
-    needs: setup
-    strategy:
-      fail-fast: false
-      matrix:
-        build: ${{ fromJson(needs.setup.outputs.subsystems) }}
-    steps:
-      - uses: actions/checkout@v4
+  # test-subsystems:
+  #   name: Test subsystems
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       build: ${{ fromJson(needs.setup.outputs.subsystems) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Resolve
-        shell: bash
-        env:
-          PROJECT: ${{ matrix.build.path }}
-          CONFIGURATION: ${{ matrix.build.configuration }}
-        run: |
-          projects=$(dirname "$PROJECT")
-          domain=$(dirname "$projects")
-          name=$(yq '.name' "$CONFIGURATION")
-          service=${PROJECT#"$domain"}
-          path=$(find "$PROJECT" -name "*.csproj" | head -n1)
-          paths=$(for item in $(echo "$projects/"* "$projects"/../Shared); do test -d "$item" && find "$item" -name "*.csproj" || true; done)
-          migration="$domain/migrations/$(basename "$PROJECT").sql"
-          if [ ! -f "$migration" ]; then
-            migration=""
-          fi
+  #     - name: Resolve
+  #       shell: bash
+  #       env:
+  #         PROJECT: ${{ matrix.build.path }}
+  #         CONFIGURATION: ${{ matrix.build.configuration }}
+  #       run: |
+  #         projects=$(dirname "$PROJECT")
+  #         domain=$(dirname "$projects")
+  #         name=$(yq '.name' "$CONFIGURATION")
+  #         service=${PROJECT#"$domain"}
+  #         path=$(find "$PROJECT" -name "*.csproj" | head -n1)
+  #         paths=$(for item in $(echo "$projects/"* "$projects"/../Shared); do test -d "$item" && find "$item" -name "*.csproj" || true; done)
+  #         migration="$domain/migrations/$(basename "$PROJECT").sql"
+  #         if [ ! -f "$migration" ]; then
+  #           migration=""
+  #         fi
 
-          EOF=$(head -c 20 /dev/random | md5sum | head -c 32)
-          {
-            printf "paths<<%s\n" "$EOF"
-            printf "%s\n" "$paths"
-            printf "%s\n" "$EOF"
-            echo "migration=${migration}"
-            echo "service=${service}"
-            echo "domain=${domain}"
-            echo "name=${name}"
-            echo "path=${path}"
-            echo "version=abcdefg"
-          } >> $GITHUB_ENV
+  #         EOF=$(head -c 20 /dev/random | md5sum | head -c 32)
+  #         {
+  #           printf "paths<<%s\n" "$EOF"
+  #           printf "%s\n" "$paths"
+  #           printf "%s\n" "$EOF"
+  #           echo "migration=${migration}"
+  #           echo "service=${service}"
+  #           echo "domain=${domain}"
+  #           echo "name=${name}"
+  #           echo "path=${path}"
+  #           echo "version=abcdefg"
+  #         } >> $GITHUB_ENV
 
-      - name: Validate project
-        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') }} == false
-        uses: ./.github/actions/dotnet-validate
-        with:
-          dotnet-version: ${{ matrix.build.sdkVersion }}
-          pin-version: true
-          paths: ${{ env.paths }}
-          sql-file: ${{ env.migration }}
+  #     - name: Validate project
+  #       if: ${{ (github.event_name == 'push' && github.ref_name == 'main') }} == false
+  #       uses: ./.github/actions/dotnet-validate
+  #       with:
+  #         dotnet-version: ${{ matrix.build.sdkVersion }}
+  #         pin-version: true
+  #         paths: ${{ env.paths }}
+  #         sql-file: ${{ env.migration }}
 
   test-nugets:
     name: Test nugets
@@ -134,38 +134,38 @@ jobs:
           dotnet-version: ${{ env.SDK_VERSION }}
           upload: false
 
-  test-dockers:
-    name: Test dockers
-    runs-on: ubuntu-latest
-    needs: setup
-    strategy:
-      fail-fast: false
-      matrix:
-        path: ${{ fromJson(needs.setup.outputs.dockers) }}
-    steps:
-      - uses: actions/checkout@v4
+  # test-dockers:
+  #   name: Test dockers
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       path: ${{ fromJson(needs.setup.outputs.dockers) }}
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - name: Prepare variables
-        shell: bash
-        run: |
-          directory="${{ matrix.path }}"
-          context="$directory"
-          docker="$directory/Dockerfile"
-          configuration="$directory/configuration.yaml"
-          name=$(yq '.name' "$configuration")
+  #     - name: Prepare variables
+  #       shell: bash
+  #       run: |
+  #         directory="${{ matrix.path }}"
+  #         context="$directory"
+  #         docker="$directory/Dockerfile"
+  #         configuration="$directory/configuration.yaml"
+  #         name=$(yq '.name' "$configuration")
 
-          {
-            echo "context=$context"
-            echo "docker=$docker"
-            echo "name=$name"
-            echo "version=abcdefg"
-          } >> "$GITHUB_ENV"
+  #         {
+  #           echo "context=$context"
+  #           echo "docker=$docker"
+  #           echo "name=$name"
+  #           echo "version=abcdefg"
+  #         } >> "$GITHUB_ENV"
 
-      - name: Push image
-        uses: ./.github/actions/docker-build-and-push
-        with:
-          dockerfile: ${{ env.docker }}
-          image-name: ${{ env.name }}
-          image-tag: ${{ env.version }}
-          docker-context: ${{ env.context }}
-          dry-run: true
+  #     - name: Push image
+  #       uses: ./.github/actions/docker-build-and-push
+  #       with:
+  #         dockerfile: ${{ env.docker }}
+  #         image-name: ${{ env.name }}
+  #         image-tag: ${{ env.version }}
+  #         docker-context: ${{ env.context }}
+  #         dry-run: true
